# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=250)),
                ('desc', models.TextField(max_length=250)),
                ('value', models.IntegerField()),
                ('studyhall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.StudyHall')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField(max_length=250)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='enquiry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Student'),
        ),
    ]
