# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-24 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20180722_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyhall',
            name='hall_pic',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to=b''),
        ),
    ]
