# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20180722_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyhall',
            name='pic',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
