# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-24 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_studyhall_hall_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 14, 25, 17, 257000)),
        ),
        migrations.AddField(
            model_name='course',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='user_create',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.UserProfile'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 14, 25, 17, 257000)),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='user_create',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.UserProfile'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 14, 25, 17, 257000)),
        ),
        migrations.AddField(
            model_name='expenses',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='user_create',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.UserProfile'),
        ),
        migrations.AddField(
            model_name='student',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 14, 25, 17, 257000)),
        ),
        migrations.AddField(
            model_name='student',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='user_create',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.UserProfile'),
        ),
        migrations.AddField(
            model_name='studyhall',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 14, 25, 17, 257000)),
        ),
        migrations.AddField(
            model_name='studyhall',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyhall',
            name='user_create',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.UserProfile'),
        ),
    ]
