# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_model1_model2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='model1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='model2',
            name='id',
        ),
        migrations.AddField(
            model_name='model1',
            name='migrationmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.MigrationModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model2',
            name='migrationmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.MigrationModel'),
            preserve_default=False,
        ),
    ]
