# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20180809_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model1',
            name='migrationmodel_ptr',
        ),
        migrations.RemoveField(
            model_name='model2',
            name='migrationmodel_ptr',
        ),
        migrations.AddField(
            model_name='model1',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model2',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MigrationModel',
        ),
    ]
