# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20180809_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('s', 'student'), ('ss', 'studyspace')], default='s', max_length=2),
        ),
    ]
