# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20180810_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='up_name',
        ),
    ]
