# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20180727_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studyhall',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
